### ISSUE TITLE
Azure Blob Storage - Error: Unable to extract accountName with provided information.

### ISSUE THREAD

**Issue by dawogid** [sorry-cypress/charts#226]
## Summary

Hi, I'm not able to configure Azure Blob Storage while using sorry-cypress helm chart.
In director I get error: 

`Unable to extract accountName with provided information.\n    at getAccountNameFromUrl (/app/node_modules/@azure/storage-blob/src/utils/utils.common.ts:590:11)\n    at extractConnectionStringParts (/app/node_modules/@azure/storage-blob/src/utils/utils.common.ts:232:25)\n    at Function.fromConnectionString (/app/node_modules/@azure/storage-blob/src/BlobServiceClient.ts:386:28)\n    at Object.<anonymous> (/app/packages/director/src/screenshots/azure-blob-storage/azure-blob-storage.ts:9:45)\n    at Module._compile (node:internal/modules/cjs/loader:1191:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)\n    at Module.load (node:internal/modules/cjs/loader:1069:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:904:12)\n    at Module.require (node:internal/modules/cjs/loader:1093:19)\n    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:80:39)","type":"Error","msg":"Unable to extract accountName with provided information.`

Am I missing something?

## How to reproduce

In values.yaml set:

```
director.environmentVariables.screenshotsDriver: "../screenshots/azure-blob-storage.driver"

azureBlobStorage.containerName: "sorry-cypress"
azureBlobStorage.uploadUrlExpiryInHours: 24
azureBlobStorage.existingSecret: "azurestorageaccount"
azureBlobStorage.fullnameOverride: ""
```

Under Kubernetes namespace create secret `azurestorageaccount `containing key `connexionstring `with base64 encoded value of Azure Storage Account connection string i.e. `DefaultEndpointsProtocol=https;AccountName=examplesa ;AccountKey=kHl4QfPnJaaoAXp6sfylg7fr4MuHI3oXp4I5//kYAwmwJhVRrDZJ1CG4KuwSlD8KpVF7vVcvsx7z+AStp7zQvw==;EndpointSuffix=core.windows.net`

Make sure that Storage Account from used connection string contains container `sorry-cypress`.

Install sorry-cypress chart in same namespace as created secret `azurestorageaccount` - director will log above error.

## Environment

- cypress version: `12.13.0`
- helm chart version: `1.15.0`

**Comment by fbritoferreira** [comment]
Can you try without the base64

**Comment by dawogid** [comment]
Thank you for your answer.

As I'm aware it has to be base64 encoded, otherwise I'm not able to create Kubernetes secret.

I'm attaching files used as values.yaml and azuresotrageaccount.yaml for creating Kubernetes secret.

[azurestorageaccount.txt](https://github.com/sorry-cypress/charts/files/12165421/azurestorageaccount.txt)
[values.txt](https://github.com/sorry-cypress/charts/files/12165422/values.txt)
