### ISSUE TITLE
Enabling mongo persistence causes director to fail on startup

### ISSUE THREAD

**Issue by AsimAM** [sorry-cypress/charts#70]
After restarting the director once the api is "ready" that error is gone, but I'm not sure why this happens.

```
mongodb:
  persistence:
    enabled: true
    size: 10Gi
```

Fails with:

```
🚀 Director service is ready at http://0.0.0.0:1234/...
(node:1) UnhandledPromiseRejectionWarning: MongoServerSelectionError: connect ECONNREFUSED 10.254.255.17:27017
    at Timeout._onTimeout (/app/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mdtoro** [comment]
Any update on this?
